export const statusMap = {
    Awaiting_Content_Approval: "Awaiting Content Approval",
    Content_Approved: "Content Approved",
    Content_Rejected: "Content Rejected",
    Issue: "Issue",
    Awaiting_Shipment: "Awaiting Shipment",
    Awaiting_Content: "Awaiting Content",
    Past_Deadline: "Past Deadline",
    Request_Approved: "Awaiting Brand Approval",
    Cancelled: "Cancelled",
    Request_Rejected: "Request Rejected",
    Completed: "Completed",
    PRODUCT_ISSUE: "Product Issue",
    SHIPPING_ISSUE: "Shipping Issue",
    OTHER_ISSUE: "Other Issue",
};

export const statusColorMap = {
    Awaiting_Content_Approval: "#FFFFAD",
    Content_Approved: "#A4E504",
    Content_Rejected: "#F2424C",
    Issue: "#F2424C",
    Awaiting_Shipment: "#ffe457",
    Awaiting_Content: "#C7F6C7",
    Past_Deadline: "#FF0000",
    Request_Approved: "#FFCC33",
    Cancelled: "#F2424C",
    Request_Rejected: "#F2424C",
    Completed: "#A4E504",
    Approved: "#A4E504",
    Rejected: "#F2424C",
    Pending: "#FFCC33",
}